name: Deploy Release to Maven Central

on:
  push:
    branches:
      - master

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java and Maven with GPG
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Extract version from pom.xml
        id: get-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression='project.version' -q -DforceStdout)
          echo "Project version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and deploy release
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: mvn -B clean deploy -Psign-artifacts -DskipTests

      - name: Create Git tag for release
        run: |
          VERSION=$(mvn help:evaluate -Dexpression='project.version' -q -DforceStdout)
          echo "Creating Git tag v$VERSION"
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch --tags
          git tag "v$VERSION"
          git push origin "v$VERSION"
